const comuniPerProvincia = {
  "catanzaro": [
    "Albi",
    "Amaroni",
    "Amato",
    "Andali",
    "Argusto",
    "Badolato",
    "Belcastro",
    "Borgia",
    "Botricello",
    "Caraffa di Catanzaro",
    "Cardinale",
    "Carlopoli",
    "Catanzaro",
    "Cenadi",
    "Centrache",
    "Cerva",
    "Chiaravalle Centrale",
    "Cicala",
    "Conflenti",
    "Cortale",
    "Cropani",
    "Curinga",
    "Davoli",
    "Decollatura",
    "Falerna",
    "Feroleto Antico",
    "Fossato Serralta",
    "Gagliato",
    "Gasperina",
    "Gimigliano",
    "Girifalco",
    "Gizzeria",
    "Guardavalle",
    "Isca sullo Ionio",
    "Jacurso",
    "Lamezia Terme",
    "Magisano",
    "Maida",
    "Marcedusa",
    "Marcellinara",
    "Martirano",
    "Martirano Lombardo",
    "Miglierina",
    "Montauro",
    "Montepaone",
    "Motta Santa Lucia",
    "Nocera Terinese",
    "Olivadi",
    "Palermiti",
    "Pentone",
    "Petrizzi",
    "Petronà",
    "Pianopoli",
    "Platania",
    "San Floro",
    "San Mango d'Aquino",
    "San Pietro a Maida",
    "San Pietro Apostolo",
    "San Sostene",
    "San Vito sullo Ionio",
    "Santa Caterina dello Ionio",
    "Sant'Andrea Apostolo dello Ionio",
    "Satriano",
    "Sellia",
    "Sellia Marina",
    "Serrastretta",
    "Sersale",
    "Settingiano",
    "Simeri Crichi",
    "Sorbo San Basile",
    "Soverato",
    "Soveria Mannelli",
    "Soveria Simeri",
    "Squillace",
    "Stalettì",
    "Taverna",
    "Tiriolo",
    "Torre di Ruggiero",
    "Vallefiorita",
    "Zagarise"
  ],
  "cosenza": [
    "Acquaformosa",
    "Acquappesa",
    "Acri",
    "Aiello Calabro",
    "Aieta",
    "Albidona",
    "Alessandria del Carretto",
    "Altilia",
    "Altomonte",
    "Amantea",
    "Amendolara",
    "Aprigliano",
    "Belmonte Calabro",
    "Belsito",
    "Belvedere Marittimo",
    "Bianchi",
    "Bisignano",
    "Bocchigliero",
    "Bonifati",
    "Buonvicino",
    "Calopezzati",
    "Caloveto",
    "Campana",
    "Canna",
    "Cariati",
    "Carolei",
    "Carpanzano",
    "Casali del Manco",
    "Cassano all'Ionio",
    "Castiglione Cosentino",
    "Castrolibero",
    "Castroregio",
    "Castrovillari",
    "Celico",
    "Cellara",
    "Cerchiara di Calabria",
    "Cerisano",
    "Cervicati",
    "Cerzeto",
    "Cetraro",
    "Civita",
    "Cleto",
    "Colosimi",
    "Corigliano-Rossano",
    "Cosenza",
    "Cropalati",
    "Crosia",
    "Diamante",
    "Dipignano",
    "Domanico",
    "Fagnano Castello",
    "Falconara Albanese",
    "Figline Vegliaturo",
    "Firmo",
    "Fiumefreddo Bruzio",
    "Francavilla Marittima",
    "Frascineto",
    "Fuscaldo",
    "Grimaldi",
    "Grisolia",
    "Guardia Piemontese",
    "Lago",
    "Laino Borgo",
    "Laino Castello",
    "Lappano",
    "Lattarico",
    "Longobardi",
    "Longobucco",
    "Lungro",
    "Luzzi",
    "Maierà",
    "Malito",
    "Malvito",
    "Mandatoriccio",
    "Mangone",
    "Marano Marchesato",
    "Marano Principato",
    "Marzi",
    "Mendicino",
    "Mongrassano",
    "Montalto Uffugo",
    "Montegiordano",
    "Morano Calabro",
    "Mormanno",
    "Mottafollone",
    "Nocara",
    "Oriolo",
    "Orsomarso",
    "Paludi",
    "Panettieri",
    "Paola",
    "Papasidero",
    "Parenti",
    "Paterno Calabro",
    "Pedivigliano",
    "Piane Crati",
    "Pietrafitta",
    "Pietrapaola",
    "Plataci",
    "Praia a Mare",
    "Rende",
    "Rocca Imperiale",
    "Roggiano Gravina",
    "Rogliano",
    "Rose",
    "Roseto Capo Spulico",
    "Rota Greca",
    "Rovito",
    "San Basile",
    "San Benedetto Ullano",
    "San Cosmo Albanese",
    "San Demetrio Corone",
    "San Donato di Ninea",
    "San Fili",
    "San Giorgio Albanese",
    "San Giovanni in Fiore",
    "San Lorenzo Bellizzi",
    "San Lorenzo del Vallo",
    "San Lucido",
    "San Marco Argentano",
    "San Martino di Finita",
    "San Nicola Arcella",
    "San Pietro in Amantea",
    "San Pietro in Guarano",
    "San Sosti",
    "San Vincenzo La Costa",
    "Sangineto",
    "Santa Caterina Albanese",
    "Santa Domenica Talao",
    "Santa Maria del Cedro",
    "Santa Sofia d'Epiro",
    "Sant'Agata di Esaro",
    "Santo Stefano di Rogliano",
    "Saracena",
    "Scala Coeli",
    "Scalea",
    "Scigliano",
    "Serra d'Aiello",
    "Spezzano Albanese",
    "Spezzano della Sila",
    "Tarsia",
    "Terranova da Sibari",
    "Terravecchia",
    "Torano Castello",
    "Tortora",
    "Trebisacce",
    "Vaccarizzo Albanese",
    "Verbicaro",
    "Villapiana",
    "Zumpano"
  ],
  "crotone": [
    "Belvedere di Spinello",
    "Caccuri",
    "Carfizzi",
    "Casabona",
    "Castelsilano",
    "Cerenzia",
    "Cirò",
    "Cirò Marina",
    "Cotronei",
    "Crotone",
    "Crucoli",
    "Cutro",
    "Isola di Capo Rizzuto",
    "Melissa",
    "Mesoraca",
    "Pallagorio",
    "Petilia Policastro",
    "Rocca di Neto",
    "Roccabernarda",
    "San Mauro Marchesato",
    "San Nicola dell'Alto",
    "Santa Severina",
    "Savelli",
    "Scandale",
    "Strongoli",
    "Umbriatico",
    "Verzino"
  ],
  "reggio calabria": [
    "Africo",
    "Agnana Calabra",
    "Anoia",
    "Antonimina",
    "Ardore",
    "Bagaladi",
    "Bagnara Calabra",
    "Benestare",
    "Bianco",
    "Bivongi",
    "Bova",
    "Bova Marina",
    "Bovalino",
    "Brancaleone",
    "Bruzzano Zeffirio",
    "Calanna",
    "Camini",
    "Campo Calabro",
    "Candidoni",
    "Canolo",
    "Caraffa del Bianco",
    "Cardeto",
    "Careri",
    "Casignana",
    "Caulonia",
    "Ciminà",
    "Cinquefrondi",
    "Cittanova",
    "Condofuri",
    "Cosoleto",
    "Delianuova",
    "Feroleto della Chiesa",
    "Ferruzzano",
    "Fiumara",
    "Galatro",
    "Gerace",
    "Giffone",
    "Gioia Tauro",
    "Gioiosa Ionica",
    "Grotteria",
    "Laganadi",
    "Laureana di Borrello",
    "Locri",
    "Mammola",
    "Marina di Gioiosa Ionica",
    "Maropati",
    "Martone",
    "Melicuccà",
    "Melicucco",
    "Melito di Porto Salvo",
    "Molochio",
    "Monasterace",
    "Montebello Jonico",
    "Motta San Giovanni",
    "Oppido Mamertina",
    "Palizzi",
    "Palmi",
    "Pazzano",
    "Placanica",
    "Platì",
    "Polistena",
    "Portigliola",
    "Reggio Calabria",
    "Riace",
    "Rizziconi",
    "Roccaforte del Greco",
    "Roccella Ionica",
    "Roghudi",
    "Rosarno",
    "Samo",
    "San Ferdinando",
    "San Giorgio Morgeto",
    "San Giovanni di Gerace",
    "San Lorenzo",
    "San Luca",
    "San Pietro di Caridà",
    "San Procopio",
    "San Roberto",
    "Santa Cristina d'Aspromonte",
    "Sant'Agata del Bianco",
    "Sant'Alessio in Aspromonte",
    "Sant'Eufemia d'Aspromonte",
    "Sant'Ilario dello Ionio",
    "Santo Stefano in Aspromonte",
    "Scido",
    "Scilla",
    "Seminara",
    "Serrata",
    "Siderno",
    "Sinopoli",
    "Staiti",
    "Stignano",
    "Stilo",
    "Taurianova",
    "Terranova Sappo Minulio",
    "Varapodio",
    "Villa San Giovanni"
  ],
  "vibo valentia": [
    "Acquaro",
    "Arena",
    "Briatico",
    "Brognaturo",
    "Capistrano",
    "Cessaniti",
    "Dasà",
    "Dinami",
    "Drapia",
    "Fabrizia",
    "Filadelfia",
    "Filandari",
    "Filogaso",
    "Francavilla Angitola",
    "Francica",
    "Gerocarne",
    "Ionadi",
    "Joppolo",
    "Limbadi",
    "Maierato",
    "Mileto",
    "Mongiana",
    "Monterosso Calabro",
    "Nardodipace",
    "Nicotera",
    "Parghelia",
    "Pizzo",
    "Pizzoni",
    "Polia",
    "Ricadi",
    "Rombiolo",
    "San Calogero",
    "San Costantino Calabro",
    "San Gregorio d'Ippona",
    "San Nicola da Crissa",
    "Sant'Onofrio",
    "Serra San Bruno",
    "Simbario",
    "Sorianello",
    "Soriano Calabro",
    "Spadola",
    "Spilinga",
    "Stefanaconi",
    "Tropea",
    "Vallelonga",
    "Vazzano",
    "Vibo Valentia",
    "Zaccanopoli",
    "Zambrone",
    "Zungri"
  ]
};

const comuneToProvincia = {
  "albi": "Catanzaro",
  "amaroni": "Catanzaro",
  "amato": "Catanzaro",
  "andali": "Catanzaro",
  "argusto": "Catanzaro",
  "badolato": "Catanzaro",
  "belcastro": "Catanzaro",
  "borgia": "Catanzaro",
  "botricello": "Catanzaro",
  "caraffa di catanzaro": "Catanzaro",
  "cardinale": "Catanzaro",
  "carlopoli": "Catanzaro",
  "catanzaro": "Catanzaro",
  "cenadi": "Catanzaro",
  "centrache": "Catanzaro",
  "cerva": "Catanzaro",
  "chiaravalle centrale": "Catanzaro",
  "cicala": "Catanzaro",
  "conflenti": "Catanzaro",
  "cortale": "Catanzaro",
  "cropani": "Catanzaro",
  "curinga": "Catanzaro",
  "davoli": "Catanzaro",
  "decollatura": "Catanzaro",
  "falerna": "Catanzaro",
  "feroleto antico": "Catanzaro",
  "fossato serralta": "Catanzaro",
  "gagliato": "Catanzaro",
  "gasperina": "Catanzaro",
  "gimigliano": "Catanzaro",
  "girifalco": "Catanzaro",
  "gizzeria": "Catanzaro",
  "guardavalle": "Catanzaro",
  "isca sullo ionio": "Catanzaro",
  "jacurso": "Catanzaro",
  "lamezia terme": "Catanzaro",
  "magisano": "Catanzaro",
  "maida": "Catanzaro",
  "marcedusa": "Catanzaro",
  "marcellinara": "Catanzaro",
  "martirano": "Catanzaro",
  "martirano lombardo": "Catanzaro",
  "miglierina": "Catanzaro",
  "montauro": "Catanzaro",
  "montepaone": "Catanzaro",
  "motta santa lucia": "Catanzaro",
  "nocera terinese": "Catanzaro",
  "olivadi": "Catanzaro",
  "palermiti": "Catanzaro",
  "pentone": "Catanzaro",
  "petrizzi": "Catanzaro",
  "petrona": "Catanzaro",
  "pianopoli": "Catanzaro",
  "platania": "Catanzaro",
  "san floro": "Catanzaro",
  "san mango daquino": "Catanzaro",
  "san pietro a maida": "Catanzaro",
  "san pietro apostolo": "Catanzaro",
  "san sostene": "Catanzaro",
  "san vito sullo ionio": "Catanzaro",
  "santa caterina dello ionio": "Catanzaro",
  "santandrea apostolo dello ionio": "Catanzaro",
  "satriano": "Catanzaro",
  "sellia": "Catanzaro",
  "sellia marina": "Catanzaro",
  "serrastretta": "Catanzaro",
  "sersale": "Catanzaro",
  "settingiano": "Catanzaro",
  "simeri crichi": "Catanzaro",
  "sorbo san basile": "Catanzaro",
  "soverato": "Catanzaro",
  "soveria mannelli": "Catanzaro",
  "soveria simeri": "Catanzaro",
  "squillace": "Catanzaro",
  "staletti": "Catanzaro",
  "taverna": "Catanzaro",
  "tiriolo": "Catanzaro",
  "torre di ruggiero": "Catanzaro",
  "vallefiorita": "Catanzaro",
  "zagarise": "Catanzaro",
  "acquaformosa": "Cosenza",
  "acquappesa": "Cosenza",
  "acri": "Cosenza",
  "aiello calabro": "Cosenza",
  "aieta": "Cosenza",
  "albidona": "Cosenza",
  "alessandria del carretto": "Cosenza",
  "altilia": "Cosenza",
  "altomonte": "Cosenza",
  "amantea": "Cosenza",
  "amendolara": "Cosenza",
  "aprigliano": "Cosenza",
  "belmonte calabro": "Cosenza",
  "belsito": "Cosenza",
  "belvedere marittimo": "Cosenza",
  "bianchi": "Cosenza",
  "bisignano": "Cosenza",
  "bocchigliero": "Cosenza",
  "bonifati": "Cosenza",
  "buonvicino": "Cosenza",
  "calopezzati": "Cosenza",
  "caloveto": "Cosenza",
  "campana": "Cosenza",
  "canna": "Cosenza",
  "cariati": "Cosenza",
  "carolei": "Cosenza",
  "carpanzano": "Cosenza",
  "casali del manco": "Cosenza",
  "cassano allionio": "Cosenza",
  "castiglione cosentino": "Cosenza",
  "castrolibero": "Cosenza",
  "castroregio": "Cosenza",
  "castrovillari": "Cosenza",
  "celico": "Cosenza",
  "cellara": "Cosenza",
  "cerchiara di calabria": "Cosenza",
  "cerisano": "Cosenza",
  "cervicati": "Cosenza",
  "cerzeto": "Cosenza",
  "cetraro": "Cosenza",
  "civita": "Cosenza",
  "cleto": "Cosenza",
  "colosimi": "Cosenza",
  "corigliano rossano": "Cosenza",
  "cosenza": "Cosenza",
  "cropalati": "Cosenza",
  "crosia": "Cosenza",
  "diamante": "Cosenza",
  "dipignano": "Cosenza",
  "domanico": "Cosenza",
  "fagnano castello": "Cosenza",
  "falconara albanese": "Cosenza",
  "figline vegliaturo": "Cosenza",
  "firmo": "Cosenza",
  "fiumefreddo bruzio": "Cosenza",
  "francavilla marittima": "Cosenza",
  "frascineto": "Cosenza",
  "fuscaldo": "Cosenza",
  "grimaldi": "Cosenza",
  "grisolia": "Cosenza",
  "guardia piemontese": "Cosenza",
  "lago": "Cosenza",
  "laino borgo": "Cosenza",
  "laino castello": "Cosenza",
  "lappano": "Cosenza",
  "lattarico": "Cosenza",
  "longobardi": "Cosenza",
  "longobucco": "Cosenza",
  "lungro": "Cosenza",
  "luzzi": "Cosenza",
  "maiera": "Cosenza",
  "malito": "Cosenza",
  "malvito": "Cosenza",
  "mandatoriccio": "Cosenza",
  "mangone": "Cosenza",
  "marano marchesato": "Cosenza",
  "marano principato": "Cosenza",
  "marzi": "Cosenza",
  "mendicino": "Cosenza",
  "mongrassano": "Cosenza",
  "montalto uffugo": "Cosenza",
  "montegiordano": "Cosenza",
  "morano calabro": "Cosenza",
  "mormanno": "Cosenza",
  "mottafollone": "Cosenza",
  "nocara": "Cosenza",
  "oriolo": "Cosenza",
  "orsomarso": "Cosenza",
  "paludi": "Cosenza",
  "panettieri": "Cosenza",
  "paola": "Cosenza",
  "papasidero": "Cosenza",
  "parenti": "Cosenza",
  "paterno calabro": "Cosenza",
  "pedivigliano": "Cosenza",
  "piane crati": "Cosenza",
  "pietrafitta": "Cosenza",
  "pietrapaola": "Cosenza",
  "plataci": "Cosenza",
  "praia a mare": "Cosenza",
  "rende": "Cosenza",
  "rocca imperiale": "Cosenza",
  "roggiano gravina": "Cosenza",
  "rogliano": "Cosenza",
  "rose": "Cosenza",
  "roseto capo spulico": "Cosenza",
  "rota greca": "Cosenza",
  "rovito": "Cosenza",
  "san basile": "Cosenza",
  "san benedetto ullano": "Cosenza",
  "san cosmo albanese": "Cosenza",
  "san demetrio corone": "Cosenza",
  "san donato di ninea": "Cosenza",
  "san fili": "Cosenza",
  "san giorgio albanese": "Cosenza",
  "san giovanni in fiore": "Cosenza",
  "san lorenzo bellizzi": "Cosenza",
  "san lorenzo del vallo": "Cosenza",
  "san lucido": "Cosenza",
  "san marco argentano": "Cosenza",
  "san martino di finita": "Cosenza",
  "san nicola arcella": "Cosenza",
  "san pietro in amantea": "Cosenza",
  "san pietro in guarano": "Cosenza",
  "san sosti": "Cosenza",
  "san vincenzo la costa": "Cosenza",
  "sangineto": "Cosenza",
  "santa caterina albanese": "Cosenza",
  "santa domenica talao": "Cosenza",
  "santa maria del cedro": "Cosenza",
  "santa sofia depiro": "Cosenza",
  "santagata di esaro": "Cosenza",
  "santo stefano di rogliano": "Cosenza",
  "saracena": "Cosenza",
  "scala coeli": "Cosenza",
  "scalea": "Cosenza",
  "scigliano": "Cosenza",
  "serra daiello": "Cosenza",
  "spezzano albanese": "Cosenza",
  "spezzano della sila": "Cosenza",
  "tarsia": "Cosenza",
  "terranova da sibari": "Cosenza",
  "terravecchia": "Cosenza",
  "torano castello": "Cosenza",
  "tortora": "Cosenza",
  "trebisacce": "Cosenza",
  "vaccarizzo albanese": "Cosenza",
  "verbicaro": "Cosenza",
  "villapiana": "Cosenza",
  "zumpano": "Cosenza",
  "belvedere di spinello": "Crotone",
  "caccuri": "Crotone",
  "carfizzi": "Crotone",
  "casabona": "Crotone",
  "castelsilano": "Crotone",
  "cerenzia": "Crotone",
  "ciro": "Crotone",
  "ciro marina": "Crotone",
  "cotronei": "Crotone",
  "crotone": "Crotone",
  "crucoli": "Crotone",
  "cutro": "Crotone",
  "isola di capo rizzuto": "Crotone",
  "melissa": "Crotone",
  "mesoraca": "Crotone",
  "pallagorio": "Crotone",
  "petilia policastro": "Crotone",
  "rocca di neto": "Crotone",
  "roccabernarda": "Crotone",
  "san mauro marchesato": "Crotone",
  "san nicola dellalto": "Crotone",
  "santa severina": "Crotone",
  "savelli": "Crotone",
  "scandale": "Crotone",
  "strongoli": "Crotone",
  "umbriatico": "Crotone",
  "verzino": "Crotone",
  "africo": "Reggio Calabria",
  "agnana calabra": "Reggio Calabria",
  "anoia": "Reggio Calabria",
  "antonimina": "Reggio Calabria",
  "ardore": "Reggio Calabria",
  "bagaladi": "Reggio Calabria",
  "bagnara calabra": "Reggio Calabria",
  "benestare": "Reggio Calabria",
  "bianco": "Reggio Calabria",
  "bivongi": "Reggio Calabria",
  "bova": "Reggio Calabria",
  "bova marina": "Reggio Calabria",
  "bovalino": "Reggio Calabria",
  "brancaleone": "Reggio Calabria",
  "bruzzano zeffirio": "Reggio Calabria",
  "calanna": "Reggio Calabria",
  "camini": "Reggio Calabria",
  "campo calabro": "Reggio Calabria",
  "candidoni": "Reggio Calabria",
  "canolo": "Reggio Calabria",
  "caraffa del bianco": "Reggio Calabria",
  "cardeto": "Reggio Calabria",
  "careri": "Reggio Calabria",
  "casignana": "Reggio Calabria",
  "caulonia": "Reggio Calabria",
  "cimina": "Reggio Calabria",
  "cinquefrondi": "Reggio Calabria",
  "cittanova": "Reggio Calabria",
  "condofuri": "Reggio Calabria",
  "cosoleto": "Reggio Calabria",
  "delianuova": "Reggio Calabria",
  "feroleto della chiesa": "Reggio Calabria",
  "ferruzzano": "Reggio Calabria",
  "fiumara": "Reggio Calabria",
  "galatro": "Reggio Calabria",
  "gerace": "Reggio Calabria",
  "giffone": "Reggio Calabria",
  "gioia tauro": "Reggio Calabria",
  "gioiosa ionica": "Reggio Calabria",
  "grotteria": "Reggio Calabria",
  "laganadi": "Reggio Calabria",
  "laureana di borrello": "Reggio Calabria",
  "locri": "Reggio Calabria",
  "mammola": "Reggio Calabria",
  "marina di gioiosa ionica": "Reggio Calabria",
  "maropati": "Reggio Calabria",
  "martone": "Reggio Calabria",
  "melicucca": "Reggio Calabria",
  "melicucco": "Reggio Calabria",
  "melito di porto salvo": "Reggio Calabria",
  "molochio": "Reggio Calabria",
  "monasterace": "Reggio Calabria",
  "montebello jonico": "Reggio Calabria",
  "motta san giovanni": "Reggio Calabria",
  "oppido mamertina": "Reggio Calabria",
  "palizzi": "Reggio Calabria",
  "palmi": "Reggio Calabria",
  "pazzano": "Reggio Calabria",
  "placanica": "Reggio Calabria",
  "plati": "Reggio Calabria",
  "polistena": "Reggio Calabria",
  "portigliola": "Reggio Calabria",
  "reggio calabria": "Reggio Calabria",
  "riace": "Reggio Calabria",
  "rizziconi": "Reggio Calabria",
  "roccaforte del greco": "Reggio Calabria",
  "roccella ionica": "Reggio Calabria",
  "roghudi": "Reggio Calabria",
  "rosarno": "Reggio Calabria",
  "samo": "Reggio Calabria",
  "san ferdinando": "Reggio Calabria",
  "san giorgio morgeto": "Reggio Calabria",
  "san giovanni di gerace": "Reggio Calabria",
  "san lorenzo": "Reggio Calabria",
  "san luca": "Reggio Calabria",
  "san pietro di carida": "Reggio Calabria",
  "san procopio": "Reggio Calabria",
  "san roberto": "Reggio Calabria",
  "santa cristina daspromonte": "Reggio Calabria",
  "santagata del bianco": "Reggio Calabria",
  "santalessio in aspromonte": "Reggio Calabria",
  "santeufemia daspromonte": "Reggio Calabria",
  "santilario dello ionio": "Reggio Calabria",
  "santo stefano in aspromonte": "Reggio Calabria",
  "scido": "Reggio Calabria",
  "scilla": "Reggio Calabria",
  "seminara": "Reggio Calabria",
  "serrata": "Reggio Calabria",
  "siderno": "Reggio Calabria",
  "sinopoli": "Reggio Calabria",
  "staiti": "Reggio Calabria",
  "stignano": "Reggio Calabria",
  "stilo": "Reggio Calabria",
  "taurianova": "Reggio Calabria",
  "terranova sappo minulio": "Reggio Calabria",
  "varapodio": "Reggio Calabria",
  "villa san giovanni": "Reggio Calabria",
  "acquaro": "Vibo Valentia",
  "arena": "Vibo Valentia",
  "briatico": "Vibo Valentia",
  "brognaturo": "Vibo Valentia",
  "capistrano": "Vibo Valentia",
  "cessaniti": "Vibo Valentia",
  "dasa": "Vibo Valentia",
  "dinami": "Vibo Valentia",
  "drapia": "Vibo Valentia",
  "fabrizia": "Vibo Valentia",
  "filadelfia": "Vibo Valentia",
  "filandari": "Vibo Valentia",
  "filogaso": "Vibo Valentia",
  "francavilla angitola": "Vibo Valentia",
  "francica": "Vibo Valentia",
  "gerocarne": "Vibo Valentia",
  "ionadi": "Vibo Valentia",
  "joppolo": "Vibo Valentia",
  "limbadi": "Vibo Valentia",
  "maierato": "Vibo Valentia",
  "mileto": "Vibo Valentia",
  "mongiana": "Vibo Valentia",
  "monterosso calabro": "Vibo Valentia",
  "nardodipace": "Vibo Valentia",
  "nicotera": "Vibo Valentia",
  "parghelia": "Vibo Valentia",
  "pizzo": "Vibo Valentia",
  "pizzoni": "Vibo Valentia",
  "polia": "Vibo Valentia",
  "ricadi": "Vibo Valentia",
  "rombiolo": "Vibo Valentia",
  "san calogero": "Vibo Valentia",
  "san costantino calabro": "Vibo Valentia",
  "san gregorio dippona": "Vibo Valentia",
  "san nicola da crissa": "Vibo Valentia",
  "santonofrio": "Vibo Valentia",
  "serra san bruno": "Vibo Valentia",
  "simbario": "Vibo Valentia",
  "sorianello": "Vibo Valentia",
  "soriano calabro": "Vibo Valentia",
  "spadola": "Vibo Valentia",
  "spilinga": "Vibo Valentia",
  "stefanaconi": "Vibo Valentia",
  "tropea": "Vibo Valentia",
  "vallelonga": "Vibo Valentia",
  "vazzano": "Vibo Valentia",
  "vibo valentia": "Vibo Valentia",
  "zaccanopoli": "Vibo Valentia",
  "zambrone": "Vibo Valentia",
  "zungri": "Vibo Valentia"
};
