const comuniData = [
  { comune: "albi", provincia: "catanzaro" },
  { comune: "amaroni", provincia: "catanzaro" },
  { comune: "amato", provincia: "catanzaro" },
  { comune: "andali", provincia: "catanzaro" },
  { comune: "argusto", provincia: "catanzaro" },
  { comune: "badolato", provincia: "catanzaro" },
  { comune: "belcastro", provincia: "catanzaro" },
  { comune: "borgia", provincia: "catanzaro" },
  { comune: "botricello", provincia: "catanzaro" },
  { comune: "caraffa di catanzaro", provincia: "catanzaro" },
  { comune: "cardinale", provincia: "catanzaro" },
  { comune: "carlopoli", provincia: "catanzaro" },
  { comune: "catanzaro", provincia: "catanzaro" },
  { comune: "cenadi", provincia: "catanzaro" },
  { comune: "centrache", provincia: "catanzaro" },
  { comune: "cerva", provincia: "catanzaro" },
  { comune: "chiaravalle centrale", provincia: "catanzaro" },
  { comune: "cicala", provincia: "catanzaro" },
  { comune: "conflenti", provincia: "catanzaro" },
  { comune: "cortale", provincia: "catanzaro" },
  { comune: "cropani", provincia: "catanzaro" },
  { comune: "curinga", provincia: "catanzaro" },
  { comune: "davoli", provincia: "catanzaro" },
  { comune: "decollatura", provincia: "catanzaro" },
  { comune: "falerna", provincia: "catanzaro" },
  { comune: "feroleto antico", provincia: "catanzaro" },
  { comune: "fossato serralta", provincia: "catanzaro" },
  { comune: "gagliato", provincia: "catanzaro" },
  { comune: "gasperina", provincia: "catanzaro" },
  { comune: "gimigliano", provincia: "catanzaro" },
  { comune: "girifalco", provincia: "catanzaro" },
  { comune: "gizzeria", provincia: "catanzaro" },
  { comune: "guardavalle", provincia: "catanzaro" },
  { comune: "isca sullo ionio", provincia: "catanzaro" },
  { comune: "jacurso", provincia: "catanzaro" },
  { comune: "lamezia terme", provincia: "catanzaro" },
  { comune: "magisano", provincia: "catanzaro" },
  { comune: "maida", provincia: "catanzaro" },
  { comune: "marcedusa", provincia: "catanzaro" },
  { comune: "marcellinara", provincia: "catanzaro" },
  { comune: "martirano", provincia: "catanzaro" },
  { comune: "martirano lombardo", provincia: "catanzaro" },
  { comune: "miglierina", provincia: "catanzaro" },
  { comune: "montauro", provincia: "catanzaro" },
  { comune: "montepaone", provincia: "catanzaro" },
  { comune: "motta santa lucia", provincia: "catanzaro" },
  { comune: "nocera terinese", provincia: "catanzaro" },
  { comune: "olivadi", provincia: "catanzaro" },
  { comune: "palermiti", provincia: "catanzaro" },
  { comune: "pentone", provincia: "catanzaro" },
  { comune: "petrizzi", provincia: "catanzaro" },
  { comune: "petronà", provincia: "catanzaro" },
  { comune: "pianopoli", provincia: "catanzaro" },
  { comune: "platania", provincia: "catanzaro" },
  { comune: "san floro", provincia: "catanzaro" },
  { comune: "san mango d'aquino", provincia: "catanzaro" },
  { comune: "san pietro a maida", provincia: "catanzaro" },
  { comune: "san pietro apostolo", provincia: "catanzaro" },
  { comune: "san sostene", provincia: "catanzaro" },
  { comune: "san vito sullo ionio", provincia: "catanzaro" },
  { comune: "santa caterina dello ionio", provincia: "catanzaro" },
  { comune: "sant'andrea apostolo dello ionio", provincia: "catanzaro" },
  { comune: "satriano", provincia: "catanzaro" },
  { comune: "sellia", provincia: "catanzaro" },
  { comune: "sellia marina", provincia: "catanzaro" },
  { comune: "serrastretta", provincia: "catanzaro" },
  { comune: "sersale", provincia: "catanzaro" },
  { comune: "settingiano", provincia: "catanzaro" },
  { comune: "simeri crichi", provincia: "catanzaro" },
  { comune: "sorbo san basile", provincia: "catanzaro" },
  { comune: "soverato", provincia: "catanzaro" },
  { comune: "soveria mannelli", provincia: "catanzaro" },
  { comune: "soveria simeri", provincia: "catanzaro" },
  { comune: "squillace", provincia: "catanzaro" },
  { comune: "stalettì", provincia: "catanzaro" },
  { comune: "taverna", provincia: "catanzaro" },
  { comune: "tiriolo", provincia: "catanzaro" },
  { comune: "torre di ruggiero", provincia: "catanzaro" },
  { comune: "vallefiorita", provincia: "catanzaro" },
  { comune: "zagarise", provincia: "catanzaro" },
  { comune: "acquaformosa", provincia: "cosenza" },
  { comune: "acquappesa", provincia: "cosenza" },
  { comune: "acri", provincia: "cosenza" },
  { comune: "aiello calabro", provincia: "cosenza" },
  { comune: "aieta", provincia: "cosenza" },
  { comune: "albidona", provincia: "cosenza" },
  { comune: "alessandria del carretto", provincia: "cosenza" },
  { comune: "altilia", provincia: "cosenza" },
  { comune: "altomonte", provincia: "cosenza" },
  { comune: "amantea", provincia: "cosenza" },
  { comune: "amendolara", provincia: "cosenza" },
  { comune: "aprigliano", provincia: "cosenza" },
  { comune: "belmonte calabro", provincia: "cosenza" },
  { comune: "belsito", provincia: "cosenza" },
  { comune: "belvedere marittimo", provincia: "cosenza" },
  { comune: "bianchi", provincia: "cosenza" },
  { comune: "bisignano", provincia: "cosenza" },
  { comune: "bocchigliero", provincia: "cosenza" },
  { comune: "bonifati", provincia: "cosenza" },
  { comune: "buonvicino", provincia: "cosenza" },
  { comune: "calopezzati", provincia: "cosenza" },
  { comune: "caloveto", provincia: "cosenza" },
  { comune: "campana", provincia: "cosenza" },
  { comune: "canna", provincia: "cosenza" },
  { comune: "cariati", provincia: "cosenza" },
  { comune: "carolei", provincia: "cosenza" },
  { comune: "carpanzano", provincia: "cosenza" },
  { comune: "casali del manco", provincia: "cosenza" },
  { comune: "cassano all'ionio", provincia: "cosenza" },
  { comune: "castiglione cosentino", provincia: "cosenza" },
  { comune: "castrolibero", provincia: "cosenza" },
  { comune: "castroregio", provincia: "cosenza" },
  { comune: "castrovillari", provincia: "cosenza" },
  { comune: "celico", provincia: "cosenza" },
  { comune: "cellara", provincia: "cosenza" },
  { comune: "cerchiara di calabria", provincia: "cosenza" },
  { comune: "cerisano", provincia: "cosenza" },
  { comune: "cervicati", provincia: "cosenza" },
  { comune: "cerzeto", provincia: "cosenza" },
  { comune: "cetraro", provincia: "cosenza" },
  { comune: "civita", provincia: "cosenza" },
  { comune: "cleto", provincia: "cosenza" },
  { comune: "colosimi", provincia: "cosenza" },
  { comune: "corigliano-rossano", provincia: "cosenza" },
  { comune: "cosenza", provincia: "cosenza" },
  { comune: "cropalati", provincia: "cosenza" },
  { comune: "crosia", provincia: "cosenza" },
  { comune: "diamante", provincia: "cosenza" },
  { comune: "dipignano", provincia: "cosenza" },
  { comune: "domanico", provincia: "cosenza" },
  { comune: "fagnano castello", provincia: "cosenza" },
  { comune: "falconara albanese", provincia: "cosenza" },
  { comune: "figline vegliaturo", provincia: "cosenza" },
  { comune: "firmo", provincia: "cosenza" },
  { comune: "fiumefreddo bruzio", provincia: "cosenza" },
  { comune: "francavilla marittima", provincia: "cosenza" },
  { comune: "frascineto", provincia: "cosenza" },
  { comune: "fuscaldo", provincia: "cosenza" },
  { comune: "grimaldi", provincia: "cosenza" },
  { comune: "grisolia", provincia: "cosenza" },
  { comune: "guardia piemontese", provincia: "cosenza" },
  { comune: "lago", provincia: "cosenza" },
  { comune: "laino borgo", provincia: "cosenza" },
  { comune: "laino castello", provincia: "cosenza" },
  { comune: "lappano", provincia: "cosenza" },
  { comune: "lattarico", provincia: "cosenza" },
  { comune: "longobardi", provincia: "cosenza" },
  { comune: "longobucco", provincia: "cosenza" },
  { comune: "lungro", provincia: "cosenza" },
  { comune: "luzzi", provincia: "cosenza" },
  { comune: "maierà", provincia: "cosenza" },
  { comune: "malito", provincia: "cosenza" },
  { comune: "malvito", provincia: "cosenza" },
  { comune: "mandatoriccio", provincia: "cosenza" },
  { comune: "mangone", provincia: "cosenza" },
  { comune: "marano marchesato", provincia: "cosenza" },
  { comune: "marano principato", provincia: "cosenza" },
  { comune: "marzi", provincia: "cosenza" },
  { comune: "mendicino", provincia: "cosenza" },
  { comune: "mongrassano", provincia: "cosenza" },
  { comune: "montalto uffugo", provincia: "cosenza" },
  { comune: "montegiordano", provincia: "cosenza" },
  { comune: "morano calabro", provincia: "cosenza" },
  { comune: "mormanno", provincia: "cosenza" },
  { comune: "mottafollone", provincia: "cosenza" },
  { comune: "nocara", provincia: "cosenza" },
  { comune: "oriolo", provincia: "cosenza" },
  { comune: "orsomarso", provincia: "cosenza" },
  { comune: "paludi", provincia: "cosenza" },
  { comune: "panettieri", provincia: "cosenza" },
  { comune: "paola", provincia: "cosenza" },
  { comune: "papasidero", provincia: "cosenza" },
  { comune: "parenti", provincia: "cosenza" },
  { comune: "paterno calabro", provincia: "cosenza" },
  { comune: "pedivigliano", provincia: "cosenza" },
  { comune: "piane crati", provincia: "cosenza" },
  { comune: "pietrafitta", provincia: "cosenza" },
  { comune: "pietrapaola", provincia: "cosenza" },
  { comune: "plataci", provincia: "cosenza" },
  { comune: "praia a mare", provincia: "cosenza" },
  { comune: "rende", provincia: "cosenza" },
  { comune: "rocca imperiale", provincia: "cosenza" },
  { comune: "roggiano gravina", provincia: "cosenza" },
  { comune: "rogliano", provincia: "cosenza" },
  { comune: "rose", provincia: "cosenza" },
  { comune: "roseto capo spulico", provincia: "cosenza" },
  { comune: "rota greca", provincia: "cosenza" },
  { comune: "rovito", provincia: "cosenza" },
  { comune: "san basile", provincia: "cosenza" },
  { comune: "san benedetto ullano", provincia: "cosenza" },
  { comune: "san cosmo albanese", provincia: "cosenza" },
  { comune: "san demetrio corone", provincia: "cosenza" },
  { comune: "san donato di ninea", provincia: "cosenza" },
  { comune: "san fili", provincia: "cosenza" },
  { comune: "san giorgio albanese", provincia: "cosenza" },
  { comune: "san giovanni in fiore", provincia: "cosenza" },
  { comune: "san lorenzo bellizzi", provincia: "cosenza" },
  { comune: "san lorenzo del vallo", provincia: "cosenza" },
  { comune: "san lucido", provincia: "cosenza" },
  { comune: "san marco argentano", provincia: "cosenza" },
  { comune: "san martino di finita", provincia: "cosenza" },
  { comune: "san nicola arcella", provincia: "cosenza" },
  { comune: "san pietro in amantea", provincia: "cosenza" },
  { comune: "san pietro in guarano", provincia: "cosenza" },
  { comune: "san sosti", provincia: "cosenza" },
  { comune: "san vincenzo la costa", provincia: "cosenza" },
  { comune: "sangineto", provincia: "cosenza" },
  { comune: "santa caterina albanese", provincia: "cosenza" },
  { comune: "santa domenica talao", provincia: "cosenza" },
  { comune: "santa maria del cedro", provincia: "cosenza" },
  { comune: "santa sofia d'epiro", provincia: "cosenza" },
  { comune: "sant'agata di esaro", provincia: "cosenza" },
  { comune: "santo stefano di rogliano", provincia: "cosenza" },
  { comune: "saracena", provincia: "cosenza" },
  { comune: "scala coeli", provincia: "cosenza" },
  { comune: "scalea", provincia: "cosenza" },
  { comune: "scigliano", provincia: "cosenza" },
  { comune: "serra d'aiello", provincia: "cosenza" },
  { comune: "spezzano albanese", provincia: "cosenza" },
  { comune: "spezzano della sila", provincia: "cosenza" },
  { comune: "tarsia", provincia: "cosenza" },
  { comune: "terranova da sibari", provincia: "cosenza" },
  { comune: "terravecchia", provincia: "cosenza" },
  { comune: "torano castello", provincia: "cosenza" },
  { comune: "tortora", provincia: "cosenza" },
  { comune: "trebisacce", provincia: "cosenza" },
  { comune: "vaccarizzo albanese", provincia: "cosenza" },
  { comune: "verbicaro", provincia: "cosenza" },
  { comune: "villapiana", provincia: "cosenza" },
  { comune: "zumpano", provincia: "cosenza" },
  { comune: "belvedere di spinello", provincia: "crotone" },
  { comune: "caccuri", provincia: "crotone" },
  { comune: "carfizzi", provincia: "crotone" },
  { comune: "casabona", provincia: "crotone" },
  { comune: "castelsilano", provincia: "crotone" },
  { comune: "cerenzia", provincia: "crotone" },
  { comune: "cirò", provincia: "crotone" },
  { comune: "cirò marina", provincia: "crotone" },
  { comune: "cotronei", provincia: "crotone" },
  { comune: "crotone", provincia: "crotone" },
  { comune: "crucoli", provincia: "crotone" },
  { comune: "cutro", provincia: "crotone" },
  { comune: "isola di capo rizzuto", provincia: "crotone" },
  { comune: "melissa", provincia: "crotone" },
  { comune: "mesoraca", provincia: "crotone" },
  { comune: "pallagorio", provincia: "crotone" },
  { comune: "petilia policastro", provincia: "crotone" },
  { comune: "rocca di neto", provincia: "crotone" },
  { comune: "roccabernarda", provincia: "crotone" },
  { comune: "san mauro marchesato", provincia: "crotone" },
  { comune: "san nicola dell'alto", provincia: "crotone" },
  { comune: "santa severina", provincia: "crotone" },
  { comune: "savelli", provincia: "crotone" },
  { comune: "scandale", provincia: "crotone" },
  { comune: "strongoli", provincia: "crotone" },
  { comune: "umbriatico", provincia: "crotone" },
  { comune: "verzino", provincia: "crotone" },
  { comune: "africo", provincia: "reggio calabria" },
  { comune: "agnana calabra", provincia: "reggio calabria" },
  { comune: "anoia", provincia: "reggio calabria" },
  { comune: "antonimina", provincia: "reggio calabria" },
  { comune: "ardore", provincia: "reggio calabria" },
  { comune: "bagaladi", provincia: "reggio calabria" },
  { comune: "bagnara calabra", provincia: "reggio calabria" },
  { comune: "benestare", provincia: "reggio calabria" },
  { comune: "bianco", provincia: "reggio calabria" },
  { comune: "bivongi", provincia: "reggio calabria" },
  { comune: "bova", provincia: "reggio calabria" },
  { comune: "bova marina", provincia: "reggio calabria" },
  { comune: "bovalino", provincia: "reggio calabria" },
  { comune: "brancaleone", provincia: "reggio calabria" },
  { comune: "bruzzano zeffirio", provincia: "reggio calabria" },
  { comune: "calanna", provincia: "reggio calabria" },
  { comune: "camini", provincia: "reggio calabria" },
  { comune: "campo calabro", provincia: "reggio calabria" },
  { comune: "candidoni", provincia: "reggio calabria" },
  { comune: "canolo", provincia: "reggio calabria" },
  { comune: "caraffa del bianco", provincia: "reggio calabria" },
  { comune: "cardeto", provincia: "reggio calabria" },
  { comune: "careri", provincia: "reggio calabria" },
  { comune: "casignana", provincia: "reggio calabria" },
  { comune: "caulonia", provincia: "reggio calabria" },
  { comune: "ciminà", provincia: "reggio calabria" },
  { comune: "cinquefrondi", provincia: "reggio calabria" },
  { comune: "cittanova", provincia: "reggio calabria" },
  { comune: "condofuri", provincia: "reggio calabria" },
  { comune: "cosoleto", provincia: "reggio calabria" },
  { comune: "delianuova", provincia: "reggio calabria" },
  { comune: "feroleto della chiesa", provincia: "reggio calabria" },
  { comune: "ferruzzano", provincia: "reggio calabria" },
  { comune: "fiumara", provincia: "reggio calabria" },
  { comune: "galatro", provincia: "reggio calabria" },
  { comune: "gerace", provincia: "reggio calabria" },
  { comune: "giffone", provincia: "reggio calabria" },
  { comune: "gioia tauro", provincia: "reggio calabria" },
  { comune: "gioiosa ionica", provincia: "reggio calabria" },
  { comune: "grotteria", provincia: "reggio calabria" },
  { comune: "laganadi", provincia: "reggio calabria" },
  { comune: "laureana di borrello", provincia: "reggio calabria" },
  { comune: "locri", provincia: "reggio calabria" },
  { comune: "mammola", provincia: "reggio calabria" },
  { comune: "marina di gioiosa ionica", provincia: "reggio calabria" },
  { comune: "maropati", provincia: "reggio calabria" },
  { comune: "martone", provincia: "reggio calabria" },
  { comune: "melicuccà", provincia: "reggio calabria" },
  { comune: "melicucco", provincia: "reggio calabria" },
  { comune: "melito di porto salvo", provincia: "reggio calabria" },
  { comune: "molochio", provincia: "reggio calabria" },
  { comune: "monasterace", provincia: "reggio calabria" },
  { comune: "montebello jonico", provincia: "reggio calabria" },
  { comune: "motta san giovanni", provincia: "reggio calabria" },
  { comune: "oppido mamertina", provincia: "reggio calabria" },
  { comune: "palizzi", provincia: "reggio calabria" },
  { comune: "palmi", provincia: "reggio calabria" },
  { comune: "pazzano", provincia: "reggio calabria" },
  { comune: "placanica", provincia: "reggio calabria" },
  { comune: "platì", provincia: "reggio calabria" },
  { comune: "polistena", provincia: "reggio calabria" },
  { comune: "portigliola", provincia: "reggio calabria" },
  { comune: "reggio calabria", provincia: "reggio calabria" },
  { comune: "riace", provincia: "reggio calabria" },
  { comune: "rizziconi", provincia: "reggio calabria" },
  { comune: "roccaforte del greco", provincia: "reggio calabria" },
  { comune: "roccella ionica", provincia: "reggio calabria" },
  { comune: "roghudi", provincia: "reggio calabria" },
  { comune: "rosarno", provincia: "reggio calabria" },
  { comune: "samo", provincia: "reggio calabria" },
  { comune: "san ferdinando", provincia: "reggio calabria" },
  { comune: "san giorgio morgeto", provincia: "reggio calabria" },
  { comune: "san giovanni di gerace", provincia: "reggio calabria" },
  { comune: "san lorenzo", provincia: "reggio calabria" },
  { comune: "san luca", provincia: "reggio calabria" },
  { comune: "san pietro di caridà", provincia: "reggio calabria" },
  { comune: "san procopio", provincia: "reggio calabria" },
  { comune: "san roberto", provincia: "reggio calabria" },
  { comune: "santa cristina d'aspromonte", provincia: "reggio calabria" },
  { comune: "sant'agata del bianco", provincia: "reggio calabria" },
  { comune: "sant'alessio in aspromonte", provincia: "reggio calabria" },
  { comune: "sant'eufemia d'aspromonte", provincia: "reggio calabria" },
  { comune: "sant'ilario dello ionio", provincia: "reggio calabria" },
  { comune: "santo stefano in aspromonte", provincia: "reggio calabria" },
  { comune: "scido", provincia: "reggio calabria" },
  { comune: "scilla", provincia: "reggio calabria" },
  { comune: "seminara", provincia: "reggio calabria" },
  { comune: "serrata", provincia: "reggio calabria" },
  { comune: "siderno", provincia: "reggio calabria" },
  { comune: "sinopoli", provincia: "reggio calabria" },
  { comune: "staiti", provincia: "reggio calabria" },
  { comune: "stignano", provincia: "reggio calabria" },
  { comune: "stilo", provincia: "reggio calabria" },
  { comune: "taurianova", provincia: "reggio calabria" },
  { comune: "terranova sappo minulio", provincia: "reggio calabria" },
  { comune: "varapodio", provincia: "reggio calabria" },
  { comune: "villa san giovanni", provincia: "reggio calabria" },
  { comune: "acquaro", provincia: "vibo valentia" },
  { comune: "arena", provincia: "vibo valentia" },
  { comune: "briatico", provincia: "vibo valentia" },
  { comune: "brognaturo", provincia: "vibo valentia" },
  { comune: "capistrano", provincia: "vibo valentia" },
  { comune: "cessaniti", provincia: "vibo valentia" },
  { comune: "dasà", provincia: "vibo valentia" },
  { comune: "dinami", provincia: "vibo valentia" },
  { comune: "drapia", provincia: "vibo valentia" },
  { comune: "fabrizia", provincia: "vibo valentia" },
  { comune: "filadelfia", provincia: "vibo valentia" },
  { comune: "filandari", provincia: "vibo valentia" },
  { comune: "filogaso", provincia: "vibo valentia" },
  { comune: "francavilla angitola", provincia: "vibo valentia" },
  { comune: "francica", provincia: "vibo valentia" },
  { comune: "gerocarne", provincia: "vibo valentia" },
  { comune: "ionadi", provincia: "vibo valentia" },
  { comune: "joppolo", provincia: "vibo valentia" },
  { comune: "limbadi", provincia: "vibo valentia" },
  { comune: "maierato", provincia: "vibo valentia" },
  { comune: "mileto", provincia: "vibo valentia" },
  { comune: "mongiana", provincia: "vibo valentia" },
  { comune: "monterosso calabro", provincia: "vibo valentia" },
  { comune: "nardodipace", provincia: "vibo valentia" },
  { comune: "nicotera", provincia: "vibo valentia" },
  { comune: "parghelia", provincia: "vibo valentia" },
  { comune: "pizzo", provincia: "vibo valentia" },
  { comune: "pizzoni", provincia: "vibo valentia" },
  { comune: "polia", provincia: "vibo valentia" },
  { comune: "ricadi", provincia: "vibo valentia" },
  { comune: "rombiolo", provincia: "vibo valentia" },
  { comune: "san calogero", provincia: "vibo valentia" },
  { comune: "san costantino calabro", provincia: "vibo valentia" },
  { comune: "san gregorio d'ippona", provincia: "vibo valentia" },
  { comune: "san nicola da crissa", provincia: "vibo valentia" },
  { comune: "sant'onofrio", provincia: "vibo valentia" },
  { comune: "serra san bruno", provincia: "vibo valentia" },
  { comune: "simbario", provincia: "vibo valentia" },
  { comune: "sorianello", provincia: "vibo valentia" },
  { comune: "soriano calabro", provincia: "vibo valentia" },
  { comune: "spadola", provincia: "vibo valentia" },
  { comune: "spilinga", provincia: "vibo valentia" },
  { comune: "stefanaconi", provincia: "vibo valentia" },
  { comune: "tropea", provincia: "vibo valentia" },
  { comune: "vallelonga", provincia: "vibo valentia" },
  { comune: "vazzano", provincia: "vibo valentia" },
  { comune: "vibo valentia", provincia: "vibo valentia" },
  { comune: "zaccanopoli", provincia: "vibo valentia" },
  { comune: "zambrone", provincia: "vibo valentia" },
  { comune: "zungri", provincia: "vibo valentia" },
];